# Generated by Django 5.0.2 on 2026-06-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='опис користувача'),
        ),
    ]
