# Generated by Django 5.0.2 on 2026-09-15 18:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brand_category_species_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_image_path),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_image_path),
        ),
    ]
