# Generated by Django 5.0.2 on 2026-07-01 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='заголовок поста')),
                ('description', models.TextField(max_length=500, verbose_name='текст поста')),
                ('img', models.ImageField(blank=True, upload_to='image/users_media/posts_images/%Y', verbose_name='зображеня')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
